spring:
  application:
    name: custom_rabbit_framework
  main:
    allow-bean-definition-overriding: true
# 本地
#  rabbitmq:
#    addresses: ${RABBIT1:192.168.18.100}:5672
#    username: ${RABBIT_MQ_USERNAME:guest}
#    password: ${RABBIT_MQ_PASSWORD:123456}
#    publisher-confirms: true
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual
#        retry:
#          #60秒后重试
#          initial-interval: 60000
#          #启用发布重试
#          enabled: true
#          #传递消息的最大尝试次数
#          max-attempts: 3
#          #尝试的最大时间间隔
#          max-interval: 60000
#          #应用于先前传递重试时间间隔的乘数
#          multiplier: 1.0
# 远程
  rabbitmq:
    addresses: ${RABBIT1:10.28.20.10}:31401,${RABBIT2:10.28.20.18}:31401,${RABBIT3:10.28.20.24}:31401
    username: ${RABBIT_MQ_USERNAME:MY_USER}
    password: ${RABBIT_MQ_PASSWORD:}
    publisher-confirms: true
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          #60秒后重试
          initial-interval: 60000
          #启用发布重试
          enabled: true
          #传递消息的最大尝试次数
          max-attempts: 3
          #尝试的最大时间间隔
          max-interval: 60000
          #应用于先前传递重试时间间隔的乘数
          multiplier: 1.0